version: '3.8'

services:
  progress-ms:
    image: forum-be:latest
    env_file:
      - .env
    ports:
      - 3000:3000
#    networks:
#      - app-network
#networks:
#  app-network:
#    driver: overlay